#!/usr/bin/python
import tornado.web
import tornado.ioloop
from api import MainHandler, BodyStreamHandler, RemoteUploadHandler
from ui import FSUIHandler, StatsUIHandler
from intl import InternalHandler

import settings

application = tornado.web.Application([
    (r"/data/(.*)", MainHandler),
    (r"/ui/", tornado.web.RedirectHandler, {"url":"/ui/stats/", "permanent":False}),

    (r"/ui/fs/(.*)", FSUIHandler),
    (r"/ui/stats/", StatsUIHandler),

    (r'/static/(.*)', tornado.web.StaticFileHandler, {'path': settings.staticdir}),

    (r"/", tornado.web.RedirectHandler, {"url":"/ui/", "permanent":False}),

    (r"/intl/", InternalHandler),

    (r"/remote_upload/", RemoteUploadHandler),
], debug=True)


body_handlers = [
    ("application/octet-stream", BodyStreamHandler),
]

if __name__ == "__main__":
    import tornado.options
    tornado.options.parse_command_line()

    address = settings.internal_ip
    application.listen(8080, address=address, body_handlers=body_handlers)
    tornado.ioloop.IOLoop.instance().start()
