#!/usr/bin/python
import tornado.web
import tornado.ioloop
from api import MainHandler
from ui import UIHandler

import settings

application = tornado.web.Application([
    (r"/data/(.*)", MainHandler),
    (r"/ui/fs/", UIHandler),
    (r'/ui/fs/(.*)', tornado.web.StaticFileHandler, {'path': settings.staticdir}),
    (r"/", tornado.web.RedirectHandler, {"url":"/ui/", "permanent":False}),
])

if __name__ == "__main__":
    address = settings.internal_ip
    application.listen(8080, address=address)
    tornado.ioloop.IOLoop.instance().start()
